development:
  server: 127.0.0.1
  connection_type: normal      
  database: bootstrap_example_app_core_development

test:
  server: 127.0.0.1            
  connection_type: normal      
  database: bootstrap_example_app_core_test

production:
  servers:
    - "127.0.0.1:27017"     
    - "127.0.0.1:27017"    
    - "127.0.0.1:27017"    
  connection_type: replica_set 
  database: bootstrap_example_app_core_staging

