#!/usr/bin/env ruby
require 'rubygems'
require 'bundler'
Bundler.require
require 'active_support/inflector'
require 'fileutils'

case ARGV[0]
when 'new'
  if ARGV[1].nil?
    puts 'Invalid application name'
    exit
  end
  app_name = ARGV[1].underscore

  camelized_app_name  = app_name.camelize
  dashesized_app_name = app_name.dasherize

  root_path     = File.expand_path("../..", __FILE__)
  template_path = File.join root_path, 'lib', 'template', '.'

  current_path  = File.expand_path(".")

  app_path = File.join(current_path, dashesized_app_name)

  puts "Creating path #{app_path}"
  if Dir.exists?(app_path)
    puts "Path #{app_path} already exists"
    exit 1
  end
  Dir.mkdir app_path

  Dir.chdir(app_path) do
    puts "Copying files"
    FileUtils.cp_r template_path, ".", :preserve => true
    puts "Renaming file content"
    `grep -Irl "Ricque" . | xargs sed -i '' 's/Ricque/#{camelized_app_name}/g'`
    `grep -Irl "ricque" . | xargs sed -i '' 's/ricque/#{dashesized_app_name}/g'`
    puts "Renaming files"
    FileUtils.mv 'lib/ricque', "lib/#{dashesized_app_name}"
    FileUtils.mv "lib/ricque.rb", "lib/#{dashesized_app_name}.rb"
    FileUtils.mv "lib/tasks/ricque.rake", "lib/tasks/#{dashesized_app_name}.rake"
  end

  puts "Application created on path #{app_path}"
else
  puts "Usage: ricque new [app_name]"
end